title:            Braga Open Device Labs
tagline:          Our goal is to help portuguese’s developers, designers and entrepreneurs test, iterate and launch their ideas into great apps and mobile web sites.
description:      An awesome Jekyll theme for Open Device Labs by Pedro Polonia, based inHossain Mohd Faysal's Theme HMFAYSAL v2.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://polonia.github.io

# Owner/author information
owner:
  name:           Pedro David Polonia
  avatar:         bio-photo.jpg
  bio:            "Pedro Polonia is the father of Joao and Julia, holds a Pedro holds a master in Informatics and Computing Engineering 
 and earns a living as a programmer, working in various languages ​​(. NET, C, C++, Java, Javacript, php, rails, python), various database (Oracle, MySQL, MongoDB ) and various frameworks. He is seizing new opportunities and challenges. 
<br/>
<br/>When not programming, he enjoys traveling and having fun with his family, learn more with Audacity or Coursera courses, see videos of Robert Martin (Uncle Bob), go to meetups or visit a hacker space."
  # a Mathematician based in Doha, Qatar. His interests are anything that’s related to math, from math itself to programming languages to music to physics to engineering to philosophy."
  email:          polonia2@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        polonia
  facebook:       pedro.polonia
  github:         polonia
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  # hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-39365944-4
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Setup
    url: /theme-setup/
  - title: T-Details
    url: /technical-details/
  - title: About Pedro
    url: http://about.me/polonia
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Lisbon
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]